### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by ShawnJohnston** [ShawnJohnston/DnD-Character-Creator#1]
1. If the user assigns Background/Class and then assigns Race, AC is reset to 0.  Issue likely to be related to ability modifiers changing due to race selection.
Areas to check: Dashboard class, RefreshValues() method in program main, Menu()>>switch(Race)>>RaceConditionals pipeline.

**Comment by herrozerro** [comment]
I submitted a PR for this issue.

**Comment by ShawnJohnston** [comment]
Thank you for the help, kind stranger.
